language: r
r:
  - release

bioc_required: true

cache: 
  packages: true
sudo: required
warnings_are_errors: false
dist: xenial

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - libnetcdf-dev
      - netcdf-bin
      - libhdf5-dev

after_success:
    - Rscript -e 'covr::codecov()'