language: r
r: bioc-release
cache: 
  packages: true
sudo: required
warnings_are_errors: false
dist: xenial

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev

r_github_packages: computational-metabolomics/pmp@R_3.6.x

after_success:
    - Rscript -e 'covr::codecov()'